version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam package --template-file template.yml --output-template-file package.yml --s3-bucket aws-codepipeline-experiment
